# This file is now intentionally left blank.
# The user-related Pydantic models (UserCreate, UserPublic) are now dynamically
# generated by the `init_auth` function in `tsecure_auth.core.config`.
# This allows developers to customize the fields required for registration
# and the data returned in public user objects.
